name: flower
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.11.26
  - contourpy=1.2.0
  - cycler=0.11.0
  - filelock=3.13.1
  - fonttools=4.51.0
  - freetype=2.12.1
  - fsspec=2024.6.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - grpcio=1.62.2
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - kiwisolver=1.4.4
  - lcms2=2.12
  - lerc=3.0
  - libabseil=20240116.2
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcxx=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libgrpc=1.62.2
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=4.25.3
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - networkx=3.3
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.5.2
  - openssl=3.0.15
  - packaging=24.1
  - pillow=10.4.0
  - pip=24.2
  - pyparsing=3.2.0
  - python=3.10.15
  - python-dateutil=2.9.0post0
  - pytorch=2.3.0
  - re2=2022.04.01
  - readline=8.2
  - scikit-learn=1.5.1
  - scipy=1.14.1
  - setuptools=75.1.0
  - six=1.16.0
  - sleef=3.5.1
  - sqlite=3.45.3
  - sympy=1.13.2
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - torchaudio=2.3.0
  - torchvision=0.18.1
  - tornado=6.4.1
  - typing_extensions=4.11.0
  - unicodedata2=15.1.0
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.9.3
      - attrs==24.2.0
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - click==8.0.4
      - distlib==0.3.9
      - flwr==1.4.0
      - frozenlist==1.4.1
      - grpcio-tools==1.42.0
      - hydra-core==1.3.2
      - idna==3.10
      - iterators==0.0.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - msgpack==1.1.0
      - omegaconf==2.3.0
      - pandas==2.2.3
      - platformdirs==4.3.6
      - protobuf==3.20.3
      - pytz==2024.2
      - pyyaml==6.0.2
      - ray==1.13.0
      - referencing==0.35.1
      - requests==2.32.3
      - rpds-py==0.20.0
      - tzdata==2024.2
      - urllib3==2.2.3
      - virtualenv==20.26.6
